"""add brand insight requests table

Revision ID: 9cdc2643f295
Revises: a1b2c3d4e5f6
Create Date: 2026-01-27 23:26:43.112027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cdc2643f295'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_insight_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_brand_insight_requests_email'), 'brand_insight_requests', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_insight_requests_email'), table_name='brand_insight_requests')
    op.drop_table('brand_insight_requests')
    # ### end Alembic commands ###

