"""Initial migration

Revision ID: f917d9d152b9
Revises: 
Create Date: 2026-01-10 16:13:38.503399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f917d9d152b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_brands_website'), 'brands', ['website'], unique=True)
    op.create_table('metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('llm_name', sa.String(length=50), nullable=False),
    sa.Column('mention_rate', sa.Float(), nullable=False),
    sa.Column('citations_list', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('brand_rank', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index('ix_metrics_brand_llm', 'metrics', ['brand_id', 'llm_name'], unique=True)
    op.create_index('ix_metrics_brand_updated', 'metrics', ['brand_id', 'updated_at'], unique=False)
    op.create_table('prompts',
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_index(op.f('ix_prompts_brand_id'), 'prompts', ['brand_id'], unique=False)
    op.create_table('time_profiling',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('prompt_generation_time', sa.Float(), nullable=False),
    sa.Column('fetching_llm_response_time', sa.Float(), nullable=False),
    sa.Column('processing_response_time', sa.Float(), nullable=False),
    sa.Column('metrics_calculation_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_time_profiling_brand_id'), 'time_profiling', ['brand_id'], unique=False)
    op.create_index(op.f('ix_time_profiling_request_id'), 'time_profiling', ['request_id'], unique=False)
    op.create_table('responses',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('llm_name', sa.String(length=50), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('brands_list', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('citation_list', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.prompt_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index('ix_responses_llm_name', 'responses', ['llm_name'], unique=False)
    op.create_index('ix_responses_prompt_llm', 'responses', ['prompt_id', 'llm_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_responses_prompt_llm', table_name='responses')
    op.drop_index('ix_responses_llm_name', table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_time_profiling_request_id'), table_name='time_profiling')
    op.drop_index(op.f('ix_time_profiling_brand_id'), table_name='time_profiling')
    op.drop_table('time_profiling')
    op.drop_index(op.f('ix_prompts_brand_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('ix_metrics_brand_updated', table_name='metrics')
    op.drop_index('ix_metrics_brand_llm', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_brands_website'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###

